/**
 * STARTME Generator — converts scan data into a token-minimal orientation file.
 *
 * Output format is designed to be:
 * - Readable by ANY LLM (Claude, GPT, Gemini, Codex, Ollama)
 * - Under 50 lines for most projects
 * - Zero ambiguity — every line is actionable or informational
 * - Token-efficient — no filler, no markdown formatting, no prose
 */

/**
 * Generate STARTME.txt content from scan results.
 * @param {object} scan — output from scanner.scanProject()
 * @returns {string} — STARTME.txt content
 */
export function generate(scan) {
  const lines = [];

  // ── Line 1-2: What is this? ──
  const desc = scan.description || `${scan.name} project`;
  const stackStr = scan.stack.filter(s => !['esm', 'MIT', 'Apache-2.0', 'AGPL-3.0'].includes(s)).join(', ');
  lines.push(`${scan.name} — ${desc}`);
  if (stackStr) lines.push(`Stack: ${stackStr}`);
  lines.push('');

  // ── Commands ──
  if (Object.keys(scan.commands).length > 0) {
    lines.push('COMMANDS');
    for (const [name, cmd] of Object.entries(scan.commands)) {
      lines.push(`  ${name}: ${cmd}`);
    }
    lines.push('');
  }

  // ── Entry Points ──
  if (scan.entryPoints.length > 0) {
    lines.push('ENTRY POINTS');
    for (const ep of scan.entryPoints) {
      lines.push(`  ${ep}`);
    }
    lines.push('');
  }

  // ── Structure ──
  if (scan.structure.length > 0) {
    lines.push('STRUCTURE');
    for (const item of scan.structure) {
      lines.push(`  ${item}`);
    }
    lines.push('');
  }

  // ── Ports ──
  if (scan.ports.length > 0) {
    lines.push(`PORTS: ${scan.ports.join(', ')}`);
    lines.push('');
  }

  // ── Environment Variables ──
  if (scan.env.length > 0) {
    lines.push('ENV VARS');
    for (const v of scan.env) {
      lines.push(`  ${v}`);
    }
    lines.push('');
  }

  // ── Dependencies ──
  if (scan.deps.runtime > 0 || scan.deps.dev > 0) {
    lines.push(`DEPS: ${scan.deps.runtime} runtime, ${scan.deps.dev} dev`);
    lines.push('');
  }

  // ── License ──
  const license = scan.stack.find(s => ['MIT', 'Apache-2.0', 'AGPL-3.0'].includes(s));
  if (license) {
    lines.push(`LICENSE: ${license}`);
  }

  return lines.join('\n').trim() + '\n';
}

/**
 * Generate as a section for AGENTS.md or CLAUDE.md.
 * Wraps the output with a header.
 */
export function generateSection(scan) {
  const content = generate(scan);
  return `## Project Orientation (auto-generated by startme)\n\n\`\`\`\n${content}\`\`\`\n`;
}

/**
 * Estimate token count for the output.
 */
export function estimateTokens(text) {
  return Math.ceil(text.length / 4);
}
